url: "https://zhutom.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Tom Zhu" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - tailwind.config.js
  - netlify.toml